### ISSUE TITLE
How do YOU pronounce SKESA

### ISSUE THREAD

**Issue by tseemann** [ncbi/SKESA#10]
Paper says `called SKESA [skee–sa]`

I noticed people, including Bill Klimke, calling it "Skee - ZA" but we say "Skee - sah" here.

What do you say?

**Comment by souvorov** [comment]
We pronounce it as *skee–sa*.

**Comment by tseemann** [comment]
Summary: Bill is wrong :-)

**Comment by yaschenk** [comment]
No, Bill is Canadian. He has a birth right to pronounce it differentlly.
