### ISSUE TITLE
How to set BOOST_PATH?

### ISSUE THREAD

**Issue by chen1i6c04** [ncbi/SKESA#13]
Hi

My system is Ubuntu

I set BOOST_PATH by below command
`$ export BOOST_PATH=/netopt/ncbi_tools64/boost-1.62.0-ncbi1`

but I get the message

```
c++ -std=c++11 -c -o skesa.o skesa.cpp -D NO_NGS -Wall -Wno-format-y2k  -pthread -fPIC -O3 -finline-functions -fstrict-aliasing -fomit-frame-pointer -msse4.2 -I /netopt/ncbi_tools64/boost-1.62.0-ncbi1/include 
skesa.cpp:27:37: fatal error: boost/program_options.hpp: No such file or directory
compilation terminated.
Makefile.nongs:47: recipe for target 'skesa.o' failed
make: *** [skesa.o] Error 1
```

How do I correctly set BOOST_PATH?

**Comment by souvorov** [comment]
You can set the variable in the shell. For example in tcshell
`setenv BOOST_PATH /usr` or some other path where you have BOOST v 1.62.0
Alternatively, try `make -f Makefile.nongs BOOST_PATH=/usr` and see if it works.

**Comment by tseemann** [comment]
@chen1i6c04 `skesa` is also available in the Conda and Homebrew packaging systems.

**Comment by chen1i6c04** [comment]
I install `SKESA` by `Conda`
It can work
Thanks

**Comment by tseemann** [comment]
@chen1i6c04 i am glad it is working now. please close this issue.
