### ISSUE TITLE
WARNING: iterations are disabled

### ISSUE THREAD

**Issue by Phylloxera** [ncbi/SKESA#15]
Hello,

I saw in issue #11 that iterations are disabled by default for single-end data. I've also observed that this seems to be hard coded, ie. even when I specify `--steps 11`, I still get 'WARNING: iterations are disabled'. It seems skesa should be more powerful for single-end data (return fewer contigs) if run at multiple kmers... am I missing something important theoretically by thinking this?
Thanks!

**Comment by souvorov** [comment]
Hi Phylloxera,
Iterations with kmers up to the read length are not disabled for single-end data. This warning is usually a result of very short reads or low coverage. Could you please describe what kind of reads you use and upload the log file?

Alex

**Comment by Phylloxera** [comment]
Hi Alex,
Sorry it took so long to respond, I was on vacation. Thanks for checking on this; maybe it is a low coverage case but read length should not be an issue.  This was really just a test set of reads to see what would happen... They were originally miseq paired-end reads which assemble quite nicely with skesa but for the single end test, I conservatively merged the pairs with bbmerge and ended up with a merge rate of ~50% and ~94K reads. I could not find a log file or an option with skesa -h that would create one. Here is the console output.
[single_end_console_output.txt](https://github.com/ncbi/SKESA/files/3374728/single_end_console_output.txt)
Thanks again!

**Comment by souvorov** [comment]
Yes, it is a low coverage issue - you lost many reads after bbmerge. From the log you uploaded you can see that the average coverage is 8.86528. It is supposed to be > 10 for the default parameters. You can try --max_kmer_count 5 or lower, and you'll probably get some results. 

I'll be surprised if premerging paired reads will be more efficient than allowing skesa to do it internally.

**Comment by Phylloxera** [comment]
Good to know about the coverage count cut-off, it makes intuitive sense. And also the max_kmer_count 'fix', I'll try it! Skesa works really well on my paired-end single cell genomes with adequate coverage. The test was more thinking whether it might also be useful for single-end, metagenome, and 'dirty' viral samples in the future.
