### ISSUE TITLE
Please make new release with gfa_connector

### ISSUE THREAD

**Issue by tseemann** [ncbi/SKESA#19]
I note that there was  major commit in 2019 since 2.3.0 was released, with gfa_connector and other fixes.

It would be helpful if you could release 2.4.0 or similar.

**Comment by tseemann** [comment]
I compiled git master and it seems that
```
/skesa --version 

SKESA v.2.4.0
```
 `git tag v2.4.0 && git push --tags`  :grimacing:

**Comment by souvorov** [comment]
Standard is always good - changed.

**Comment by tseemann** [comment]
Lookinf forward to the 2.4.0 release and any other new tools you write

**Comment by souvorov** [comment]
Released :)

**Comment by tseemann** [comment]
I will work on packaging. thank you!
