### ISSUE TITLE
'Make' problem

### ISSUE THREAD

**Issue by minhtrung1997** [ncbi/SKESA#33]
I download SKESA from github, follow the steps, fix the bugs and got the Error:
[Error.log](https://github.com/ncbi/SKESA/files/7772638/Error.log)
Please help

**Comment by souvorov** [comment]
What kind of bugs? Please explain. Everything works on my side.

**Comment by minhtrung1997** [comment]
Anyway, that is the dependency error. I have installed some lib packages, delete an old NGS folder blocking the install path and upgrade CMAKE. Everything is ok now.

**Comment by souvorov** [comment]
Good :)
