### ISSUE TITLE
Mistake on to moment to install

### ISSUE THREAD

**Issue by Chris091089** [ncbi/SKESA#34]
skesa.cpp:27:10: fatal error: boost/program_options.hpp: No existe el archivo o el directorio
   27 | #include <boost/program_options.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:74: skesa.o] Error 1

**Comment by souvorov** [comment]
You need to have BOOST installed and provide path through BOOST_PATH (see compilation part in REAME.md)

**Comment by 3nrique0** [comment]
Usually requirements go BEFORE instructions to compilation.
If an outside software is required it would be only good practice to put the link or reference to the source of the tool, maybe event sometimes version.
