### ISSUE TITLE
cannot find -libboost_program_options

### ISSUE THREAD

**Issue by gregdenay** [ncbi/SKESA#37]
I installed boost version 1.81 under my home directory (`home/debian/boost`) following the doc:

```
$ cd ~/boost_1_81_0
$ ./bootstrap.sh --prefix=/home/debian//boost --exec-prefix=/home/debian/boost
$ ./b2 install
```

The  `~/boost` folder exists and contains lib/ and include/boost/ ,both of which are populated. 

When I try to build the last skesa release (skeasa.2.4.0_saute.1.3.0_2), I get the following error:

```
$ make -f Makefile.nongs BOOST_PATH=/home/debian/boost
c++ -std=c++11 -c -o skesa.o skesa.cpp -D NO_NGS -Wall -Wno-format-y2k  -pthread -fPIC -O3 -finline-functions -fstrict-aliasing -fomit-frame-pointer -msse4.2 -I /home/debian/boost/include
c++ -std=c++11 -c -o glb_align.o glb_align.cpp -D NO_NGS -Wall -Wno-format-y2k  -pthread -fPIC -O3 -finline-functions -fstrict-aliasing -fomit-frame-pointer -msse4.2 -I /home/debian/boost/include
c++ -std=c++11 -o skesa skesa.o glb_align.o -Wl,-Bstatic -L /home/debian/boost/lib -libboost_program_options -lboost_iostreams -lboost_regex -lboost_timer -lboost_chrono -lboost_system -Wl,-Bdynamic -lrt -ldl -lm  -lpthread -lz
/usr/bin/ld: cannot find -libboost_program_options
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [Makefile.nongs:79: skesa] Error 1
```

The problem does not seem to be due to the BOOST_PATH specification as removing it returns the following error:

```
$ make -f Makefile.nongs
c++ -std=c++11 -c -o skesa.o skesa.cpp -D NO_NGS -Wall -Wno-format-y2k  -pthread -fPIC -O3 -finline-functions -fstrict-aliasing -fomit-frame-pointer -msse4.2
skesa.cpp:27:10: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile.nongs:64: skesa.o] Error 1
```

Any idea what I am doing wrong here?

This is on debian 10

**Comment by gregdenay** [comment]
The same error blocks me from updating the existing bioconda recipe.
Linking relevant issue in bioconda: https://github.com/bioconda/bioconda-recipes/issues/38476
The other (possibly) connected issue in this repository: https://github.com/ncbi/SKESA/issues/32

**Comment by souvorov** [comment]
The BOOST problem you see is caused by -libboost_program_options in the make command. Unless the Makefile.nongs was modified, I don't have a good explanation. Please check that the appropriate line is -lboost_program_options \. Also check if in your BOOST lib folder you have libboost_program_options.a.
You are also missing -lz library. I believe that this is a system compression library.

**Comment by gregdenay** [comment]
Oh my. I had modified the Makefile.nongs when I tired to troubleshoot the conda recipe and forgot about it. 
With the release files building Skesa and saute works perfectly. Except for the zlib dependency, but I don't have admin rights on my system. one of the reason I am so desesperate to get the conda recipe to work.
I'll close the issue here, since it is a conda problem. If you have any insight on making it work in bioconda, the issue is still open there. Thanks for your help!

**Comment by rpetit3** [comment]
I too am having the issue, the files appear to be present, here it is for `libboost_system`

```
lrwxrwxrwx  1 robert_petit robert_petit   25 Oct 25 17:59 libboost_system.so -> libboost_system.so.1.72.0
lrwxrwxrwx  1 robert_petit robert_petit   25 Oct 25 17:59 libboost_system.so.1 -> libboost_system.so.1.72.0
lrwxrwxrwx  1 robert_petit robert_petit   25 Oct 25 17:59 libboost_system.so.1.72 -> libboost_system.so.1.72.0
-rwxr-xr-x 19 robert_petit robert_petit  15K Apr  2  2022 libboost_system.so.1.72.0

```

**Comment by souvorov** [comment]
Did you specify BOOST_PATH pointing to the boost directory which contains /lib and /include?

**Comment by rpetit3** [comment]
I did specify the BOOST_PATH variable on this one

**Comment by souvorov** [comment]
Which platform do you use? If it is Linux, the Makefile expects a static library libboost_system.a which I don't see in your list.

**Comment by rpetit3** [comment]
Ah! That is likely it! After the binaries are built is boost needed any more?

**Comment by souvorov** [comment]
If linked statically, it is not needed anymore.

**Comment by alanorth** [comment]
> Which platform do you use? If it is Linux, the Makefile expects a static library libboost_system.a which I don't see in your list.

Ah this helped. On CentOS Stream I needed to install `boost-static`.
