### ISSUE TITLE
Enable --use_paired_reads when --fastq A,B

### ISSUE THREAD

**Issue by tseemann** [ncbi/SKESA#4]
A common mistake is to forget to use `--use_paired_reads`

I argue that used case of `--fastq A,B` being paired is far more likely then it being 2 SE read sets?

Perhaps `--paired A,B` and `--unpaired A1,A2,A3` would be better?

**Comment by souvorov** [comment]
Implemented in v2.3.0. Now --use_paired_ends is needed only with a single input file containing both mates. Files separated by a comma are assumed to be paired ends.

**Comment by tseemann** [comment]
Great, thanks @souvorov !
