### ISSUE TITLE
What adapters does SKESA clip? Can I disable it?

### ISSUE THREAD

**Issue by tseemann** [ncbi/SKESA#7]
```
Adapters: 0 Reads before: 1589670 Sequence before: 234019721 Reads after: 1589670 Sequence after: 234019721
Adapters clipped in  65.247502s wall, 149.670000s user + 11.110000s system = 160.780000s CPU (246.4%)
```

In my case they have been preclipped by the NextSeq bcl2fastq, so there are no changes.

Can I disable adapter clipping? 
It took 150 user seconds which was not needed.

**Comment by souvorov** [comment]
For the adapter clipping SKESA checks the frequency of 19bp kmers. If they are found in >5% of the reads they are clipped. This behavior is regulated by --vector_percent parameter. Setting it to 1 disables clipping.

**Comment by souvorov** [comment]
The algorithm checks each 19-mer in a read from the 5' end to the 3' end. If a 19-mer was seen in more than 5% of the reads the inspected read is clipped as this point and this 19-mer and the rest of the red are removed. The clipping point can occur anywhere in the read.

Whether or not  500 hundred IS elements will trigger the clipping depends on the reads and genome lengths. If we have 500 exact copies of a 19-mer on the genome this 19-mer, on average, will be included in the 500*read_len/genome_len fraction of the reads. For a 3M genome and 250bp reads it is ~4% which is close enough to the threshold to be triggered by random variations of the coverage. 100bp reads probably will  not trigger the clipping.

Anyways, if you know that adapters are not present in the reads it is better to disable this feature.

**Comment by tseemann** [comment]
Ok, so if i know there are no adapters in my reads I should use `--vector_percent 0`.

Thank you!

**Comment by souvorov** [comment]
Yes, but it is --vector_percent 1

**Comment by tseemann** [comment]
Oh good point!
