### ISSUE TITLE
Auto-detect FASTA or FASTQ

### ISSUE THREAD

**Issue by tseemann** [ncbi/SKESA#8]
```
  --fasta arg                   Input fasta file(s) (could be used multiple
                                times for different runs) [string]
  --fastq arg                   Input fastq file(s) (could be used multiple
                                times for different runs) [string]
```

Is there a good reason for having these separate?

**Comment by souvorov** [comment]
It is a very sensible suggestion but I don't want to drastically change API so soon after our publication. I will do it with some major update.

**Comment by tseemann** [comment]
I understand.

**Comment by souvorov** [comment]
Committed a new SKESA version which can use option --reads for reading fasta or fastq files. Old options could be used but will give a warning.

**Comment by tseemann** [comment]
That's great @souvorov !
When you make a new tag we'll update Brew and Conda.
